# Generated by ops/homebrew/render-formula.py for v1.1.0-upstream8.0.7.
# Edit ops/homebrew/cli-proxy-api.rb, not this file.
class CliProxyApiAT110 < Formula
  desc "Proxy server providing OpenAI/Gemini/Claude/Codex compatible APIs"
  homepage "https://github.com/hrygo/CLIProxyAPI"
  # Declared explicitly rather than derived from the URL. Release tags carry an
  # -upstreamX.Y.Z suffix, and Homebrew's URL-derived version parsing is not
  # reliable for that shape.
  version "1.1.0-upstream8.0.7"
  license "MIT"

  keg_only :versioned

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hrygo/CLIProxyAPI/releases/download/v1.1.0-upstream8.0.7/CLIProxyAPI_1.1.0-upstream8.0.7_darwin_aarch64.tar.gz"
      sha256 "228e566273b0bd4bde80ead72de88c58d27608b0e127255b6175e08d94d121a5"
    else
      url "https://github.com/hrygo/CLIProxyAPI/releases/download/v1.1.0-upstream8.0.7/CLIProxyAPI_1.1.0-upstream8.0.7_darwin_amd64.tar.gz"
      sha256 "d19321d78e4ef07f11db6c100d6be60a144d3805149718b15780cedc4dc6470c"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/hrygo/CLIProxyAPI/releases/download/v1.1.0-upstream8.0.7/CLIProxyAPI_1.1.0-upstream8.0.7_linux_aarch64.tar.gz"
      sha256 "341592cf156b0eb8d277b320ce7019d00dcf904444e462c252b41d1b7c18b57e"
    else
      url "https://github.com/hrygo/CLIProxyAPI/releases/download/v1.1.0-upstream8.0.7/CLIProxyAPI_1.1.0-upstream8.0.7_linux_amd64.tar.gz"
      sha256 "b4d342c4d9bc090f6f64c8802c1dc74ee3530eec587a9c3d733d3fad92d0df8e"
    end
  end

  def install
    # The upstream release archive names the binary cli-proxy-api. Install it
    # as cliproxyapi so the existing launchd agent path keeps working.
    bin.install "cli-proxy-api" => "cliproxyapi"
    pkgshare.install "config.example.yaml"
  end

  def caveats
    <<~EOS
      Configuration is not managed by Homebrew. Pass your own config path:
        cliproxyapi -config #{etc}/cliproxyapi.conf

      Upgrading changes the installed binary. Restart your service manager
      separately to load it. For the existing macOS LaunchAgent:
        launchctl kickstart -k gui/$(id -u)/com.hrygo.cliproxyapi
    EOS
  end

  test do
    output = shell_output("#{bin}/cliproxyapi -h 2>&1")
    assert_match "CLIProxyAPI Version:", output
    assert_match version.to_s, output
  end
end
